import '../services/api_service.dart';

/// A teacher's AI avatar (photo + cloned voice), pending admin approval.
class TeacherAvatar {
  final int id;
  final int teacherId;
  final String? displayName;
  final String? photoUrl;
  final String? voiceSampleUrl;
  final String status; // pending | approved | rejected
  final String? rejectionReason;
  final String? voiceCloneWarning;
  final String? reviewedAt;
  final String createdAt;

  TeacherAvatar({
    required this.id,
    required this.teacherId,
    this.displayName,
    this.photoUrl,
    this.voiceSampleUrl,
    required this.status,
    this.rejectionReason,
    this.voiceCloneWarning,
    this.reviewedAt,
    required this.createdAt,
  });

  bool get isPending => status == 'pending';
  bool get isApproved => status == 'approved';
  bool get isRejected => status == 'rejected';

  factory TeacherAvatar.fromJson(Map<String, dynamic> json, ApiService api) {
    String? fixed(dynamic v) => (v == null || v.toString().isEmpty) ? null : api.fixUrl(v.toString());
    return TeacherAvatar(
      id: (json['id'] as num).toInt(),
      teacherId: (json['teacher_id'] as num?)?.toInt() ?? 0,
      displayName: json['display_name'] as String?,
      photoUrl: fixed(json['photo_url']),
      voiceSampleUrl: fixed(json['voice_sample_url']),
      status: json['status'] as String? ?? 'pending',
      rejectionReason: json['rejection_reason'] as String?,
      voiceCloneWarning: json['voice_clone_warning'] as String?,
      reviewedAt: json['reviewed_at'] as String?,
      createdAt: json['created_at'] as String? ?? '',
    );
  }
}

/// A lecture generated by a teacher's AI avatar from an uploaded presentation.
class AvatarLecture {
  final int id;
  final int avatarId;
  final int classId;
  final int createdBy;
  final String title;
  final String? sourceFilename;
  final int durationMinutes;
  final String style; // school | university | professional
  final bool autoSummary;
  final String status; // pending_approval | approved | generating | ready | rejected | failed
  final String? rejectionReason;
  final String? errorMessage;
  final String? summaryText;
  final String? introVideoUrl;
  final int estimatedChars;
  final double estimatedCostUsd;
  final String createdAt;
  final String? updatedAt;

  AvatarLecture({
    required this.id,
    required this.avatarId,
    required this.classId,
    required this.createdBy,
    required this.title,
    this.sourceFilename,
    required this.durationMinutes,
    required this.style,
    required this.autoSummary,
    required this.status,
    this.rejectionReason,
    this.errorMessage,
    this.summaryText,
    this.introVideoUrl,
    required this.estimatedChars,
    required this.estimatedCostUsd,
    required this.createdAt,
    this.updatedAt,
  });

  bool get isReady => status == 'ready';
  bool get isPendingApproval => status == 'pending_approval';
  bool get isGenerating => status == 'approved' || status == 'generating';
  bool get isRejected => status == 'rejected';
  bool get isFailed => status == 'failed';
  bool get canDelete => isPendingApproval || isRejected || isFailed;

  factory AvatarLecture.fromJson(Map<String, dynamic> json, ApiService api) {
    return AvatarLecture(
      id: (json['id'] as num).toInt(),
      avatarId: (json['avatar_id'] as num?)?.toInt() ?? 0,
      classId: (json['class_id'] as num?)?.toInt() ?? 0,
      createdBy: (json['created_by'] as num?)?.toInt() ?? 0,
      title: json['title'] as String? ?? '',
      sourceFilename: json['source_filename'] as String?,
      durationMinutes: (json['duration_minutes'] as num?)?.toInt() ?? 0,
      style: json['style'] as String? ?? 'university',
      autoSummary: json['auto_summary'] as bool? ?? true,
      status: json['status'] as String? ?? 'pending_approval',
      rejectionReason: json['rejection_reason'] as String?,
      errorMessage: json['error_message'] as String?,
      summaryText: json['summary_text'] as String?,
      introVideoUrl: (json['intro_video_url'] == null || json['intro_video_url'].toString().isEmpty)
          ? null
          : api.fixUrl(json['intro_video_url'].toString()),
      estimatedChars: (json['estimated_chars'] as num?)?.toInt() ?? 0,
      estimatedCostUsd: (json['estimated_cost_usd'] as num?)?.toDouble() ?? 0.0,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String?,
    );
  }
}

/// A single slide within a ready avatar lecture: image, narration text and audio.
class AvatarLectureSlide {
  final int id;
  final int slideIndex;
  final String? slideImageUrl;
  final String? narrationText;
  final String? audioUrl;
  final double? audioDurationSeconds;

  AvatarLectureSlide({
    required this.id,
    required this.slideIndex,
    this.slideImageUrl,
    this.narrationText,
    this.audioUrl,
    this.audioDurationSeconds,
  });

  factory AvatarLectureSlide.fromJson(Map<String, dynamic> json, ApiService api) {
    return AvatarLectureSlide(
      id: (json['id'] as num).toInt(),
      slideIndex: (json['slide_index'] as num?)?.toInt() ?? 0,
      slideImageUrl: (json['slide_image_url'] == null || json['slide_image_url'].toString().isEmpty)
          ? null
          : api.fixUrl(json['slide_image_url'].toString()),
      narrationText: json['narration_text'] as String?,
      audioUrl: (json['audio_url'] == null || json['audio_url'].toString().isEmpty)
          ? null
          : api.fixUrl(json['audio_url'].toString()),
      audioDurationSeconds: (json['audio_duration_seconds'] as num?)?.toDouble(),
    );
  }
}

/// A full lecture (metadata + slides), as returned by GET /avatars/lectures/{id}/full.
class AvatarLectureFull {
  final AvatarLecture lecture;
  final List<AvatarLectureSlide> slides;
  // The teacher's avatar photo, shown in the speaking-avatar circle. The
  // backend may embed it a few different ways depending on the endpoint
  // version, so we try several fallbacks and accept null (falls back to a
  // placeholder icon in the UI).
  final String? avatarPhotoUrl;

  AvatarLectureFull({required this.lecture, required this.slides, this.avatarPhotoUrl});

  factory AvatarLectureFull.fromJson(Map<String, dynamic> json, ApiService api) {
    final rawSlides = json['slides'];
    String? photo;
    final rawAvatar = json['avatar'];
    if (rawAvatar is Map && rawAvatar['photo_url'] != null) {
      photo = rawAvatar['photo_url'].toString();
    } else if (json['avatar_photo_url'] != null) {
      photo = json['avatar_photo_url'].toString();
    } else if (json['teacher_avatar_photo_url'] != null) {
      photo = json['teacher_avatar_photo_url'].toString();
    }
    return AvatarLectureFull(
      lecture: AvatarLecture.fromJson(json, api),
      slides: rawSlides is List
          ? rawSlides.map((s) => AvatarLectureSlide.fromJson(s as Map<String, dynamic>, api)).toList()
          : [],
      avatarPhotoUrl: (photo == null || photo.isEmpty) ? null : api.fixUrl(photo),
    );
  }
}
